theme: jekyll-theme-minimal
title: Julian Petruck
description: Welcome to my Webpage. \n I am currently doing my Masters in Machine Learning and in Philosophy at the University of Tübingen, Germany. Before that, I did my Bachelors in Cognitive Science at the University of Tübingen and was an exchange student for the Master of Logic at the Universiteit van Amsterdam.
